development:
  adapter: postgresql
  encoding: unicode
  database: seedbank_development
  pool: 5
  host: localhost
  port: 5432
production:
  adapter: postgresql
  encoding: unicode
  database: seedbank_development
  pool: 5
  host: localhost
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  database: seedbank_test
  pool: 5
  host: localhost
  port: 5432

