development:
  adapter: postgresql
  encoding: unicode
  database: seedbank_development
  pool: 5
  host: localhost
  username: postgres
  password: seedbank
  port: 5432
production:
  adapter: postgresql
  encoding: unicode
  database: seedbank_development
  pool: 5
  host: localhost
  username: postgres
  password: seedbank
  port: 5432
